VirtualHost *:80>
        ServerName localhost
        LogLevel emerg
        ServerAdmin webmaster@localhost
        DocumentRoot /www
        DirectoryIndex index.php

<Directory /www>
        AllowOverride All
        Allow from all
        Require all granted
</Directory>

</VirtualHost>
