[supervisord]
nodaemon=true

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[program:apache]
command=/usr/sbin/apache2 -DFOREGROUND
priority=3
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
killasgroup=true
stopasgroup=true
autorestart=true


[program:cron]
command=/usr/sbin/cron -f -L 15
priority=1
startinorder=true

#[program:touchrootcron]
#priority=2
#startinorder=true
#startsecs=0
#autorestart=false
#command=/bin/sleep 10 && touch /var/spool/cron/crontabs/www-data && chmod 600 /var/spool/cron/crontabs/www-data && chown www-data:crontab /var/spool/cron/crontabs/www-data

#[program:permissions]
#command=/bin/chmod -R 777 /var/spool/*
#autostart=true
#autorestart=false
#startretries=0
#redirect_stderr=false
#redirect_stderr=false
